schema_version = "1.0.0"
id = "float_curve_css"
version = "1.0.4"
name = "Float Curve CSS"
tagline = "Float Curve editing tools and Curve Profile to Float Curve"
maintainer = "Guillaume Bissieres"
type = "add-on"
website = "https://bissieres.gumroad.com/l/CurveCss"
tracker_url = "https://github.com/GuillaumeBissieres/blender-float-curve-css/issues"
tags = ["Node"]
blender_version_min = "4.2.0"
license = [
"SPDX:GPL-3.0-or-later",
]
